const { Homeroute } = require('./home')
const { Productroute } = require('./products')
const { UsersRoute } = require('./users')
const { CartRoute } = require('./cart')
const { WishlistRoute } = require('./wishlist')
const { AdminRoute } = require('./admin')
const { CategoryRoute } = require('./categories')
const { SubcategoryRoute } = require('./sub_categories')
module.exports = { Homeroute, Productroute, UsersRoute, CartRoute, WishlistRoute, AdminRoute, CategoryRoute, SubcategoryRoute }